# Generated by Django 4.2.2 on 2023-06-18 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acquista', '0002_rename_bici_bike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bike',
            options={'verbose_name_plural': 'Bici'},
        ),
    ]
