# Generated by Django 4.2.2 on 2023-06-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acquista', '0003_alter_bike_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='image',
            field=models.ImageField(default=None, upload_to='bici_images'),
        ),
    ]
