# Generated by Django 4.2.2 on 2023-06-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acquista', '0004_bike_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='bici_images'),
        ),
    ]
