# Generated by Django 4.2.2 on 2023-06-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acquista', '0007_bikeviewed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bikeviewed',
            options={'verbose_name_plural': 'Bici Viste'},
        ),
    ]
