# Generated by Django 4.2.2 on 2023-06-21 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Acquista', '0008_alter_bikeviewed_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldBike',
            fields=[
                ('bike_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Acquista.bike')),
            ],
            options={
                'verbose_name_plural': 'Bici Vendute',
            },
            bases=('Acquista.bike',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('sold_bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Acquista.soldbike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
