# Generated by Django 4.2.2 on 2023-06-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acquista', '0011_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='image',
            field=models.ImageField(upload_to='bici_images'),
        ),
    ]
