# Generated by Django 4.2.2 on 2023-06-22 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Acquista', '0013_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteBike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='Acquista.bike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Preferiti',
                'unique_together': {('user', 'bike')},
            },
        ),
    ]
