# Generated by Django 4.2.2 on 2023-06-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acquista', '0014_favoritebike'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritebike',
            name='viewed_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
