# Generated by Django 4.2.2 on 2023-06-23 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acquista', '0015_favoritebike_viewed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Telaio', 'Telaio'), ('Manubrio', 'Manubrio'), ('Freno', 'Freno'), ('Sellino', 'Sellino'), ('Copertoni', 'Copertoni')], max_length=50)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Componenti Bici',
            },
        ),
        migrations.CreateModel(
            name='CompositeBike',
            fields=[
                ('bike_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Acquista.bike')),
                ('copertoni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composite_copertoni', to='Acquista.bikecomponent')),
                ('freno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composite_freno', to='Acquista.bikecomponent')),
                ('manubrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composite_manubrio', to='Acquista.bikecomponent')),
                ('sellino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composite_sellino', to='Acquista.bikecomponent')),
                ('telaio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composite_telaio', to='Acquista.bikecomponent')),
            ],
            options={
                'verbose_name_plural': 'Bici Composte',
            },
            bases=('Acquista.bike',),
        ),
    ]
