# Generated by Django 4.2.2 on 2023-06-26 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acquista', '0017_bikecomponent_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeDiscount',
            fields=[
                ('bike_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Acquista.bike')),
                ('new_price', models.IntegerField()),
            ],
            bases=('Acquista.bike',),
        ),
    ]
