# Generated by Django 4.2.2 on 2023-06-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Acquista', '0018_bikediscount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BikeDiscount',
        ),
    ]
