# Generated by Django 4.2.2 on 2023-06-26 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acquista', '0019_delete_bikediscount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newPrice', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='Acquista.bike')),
            ],
            options={
                'verbose_name_plural': 'Sconti Bici',
            },
        ),
    ]
