# Generated by Django 4.2.2 on 2023-06-26 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Acquista', '0020_bikediscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikediscount',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='discount', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
