# Generated by Django 4.2.2 on 2023-06-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikePlace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericuser',
            name='picture',
            field=models.ImageField(blank=True, default=None, upload_to='profile_pics', verbose_name='foto profilo'),
            preserve_default=False,
        ),
    ]
